In [59]:
import pandas as pd
import numpy as np
import math
import datetime
from ipynb.fs.defs.functions import new_route
from ipynb.fs.defs.functions import get_row
from ipynb.fs.defs.functions import get_column
from ipynb.fs.defs.functions import best_index
from ipynb.fs.defs.functions import find_best_position
from ipynb.fs.defs.functions import cities_list
from ipynb.fs.defs.functions import getName

dft = pd.read_csv("../Dati/distanze/times_computed.csv", delimiter=";", encoding = "ISO-8859-1", index_col=0)
fur1 = pd.read_csv("../Dati/turni_f/2-opt1_shifts.csv", delimiter=";", encoding = "ISO-8859-1")
fur2 = pd.read_csv("../Dati/turni_f/2-opt2_shifts.csv", delimiter=";", encoding = "ISO-8859-1")

In [60]:
column = [getName(dft, x) for x in fur1["mercoledi"].dropna()]
pad = pd.Series([np.nan]*(len(fur1)-len(column)))
column = pd.concat([pd.Series(column), pad], ignore_index=True)
fur1["mercoledi"] = column

In [61]:
fur1

,lunedi,martedi,mercoledi,giovedi,venerdi
0,"Cremona, Sesto 39","Cremona, Sesto 39","Cremona, Sesto 39","Cremona, Sesto 39","Cremona, Sesto 39"
1,"Sesto ed Uniti, Roma, 4","Cremona, Ugolani Dati, 4","Castelverde, Ubaldo Ferrari, 15","Cremona, Sesto 39","Crema, Civerchi, 9"
2,"Grumello Cremonese ed Uniti, Roma, 2","Casalpusterlengo, Pusterla 7","Annicco, Giuseppe Garibaldi, 6","Cremona, Ugolani Dati, 4","Casaletto Vaprio, Maggiore, 7"
3,"Pizzighettone, Giuseppe Garibaldi, 18","Vailate, Dante Alighieri, 7","Castelleone, Roma, 67","Persico Dosimo, Albert ,7","Trescore Cremasco, Vittorio Veneto, 1"
4,"Castelleone, Roma, 67","Crema, Civerchi, 9","Madignano, Portici, 4","Grontardo, Roma, 16","Pandino, Castello, 15"
5,"Montodine, XXV Aprile, 10","Persico Dosimo, Albert ,7","Crema, Civerchi, 9","Vescovato, Roma, 44","Agnadello, Marconi, 6"
6,"Ripalta Cremasca, Roma, 5","Scandolara Ravara, Italia","Palazzo Pignano, Marco Polo, 31","Crema, Civerchi, 9","Rivolta d'Adda, Stefano Renzi, 5"
7,"Ricengo, Guglielmo Marconi","Casalmaggiore, Guglielmo Marconi, 8","Pandino, Castello, 15","Offanengo, Clavelli Martini, 5","Spino d'Adda, Circonvallazione, 13"
8,"Capralba, Piave, 2","San Giovanni in Croce, Feudatari, 25 A","Rivolta d'Adda, Stefano Renzi, 5","Izano, Gerardo da Izano, 4/C","Dovera, Oldrini 2"
9,"Sergnano, IV Novembre, 10","Ostiano, Mazzini, 1","Spino d'Adda, Circonvallazione, 13","Manerbio, INSURREZIONE NAZIONALE","Monte Cremasco, Roma, 12"
10,"Casale Cremasco-Vidolasco, Roma, 56","Ostiano, Mazzini, 1","Romanengo, Guaiarini, 14","Casalmaggiore, Guglielmo Marconi, 8","Vaiano Cremasco, Gloriosi Caduti, 3"
11,"Camisano, Trieste, 57",NaN,"Ostiano, Mazzini, 1","San Giovanni in Croce, Feudatari, 25 A","Bagnolo Cremasco, Roma, 3"
12,"Soncino, Dante Alighieri, 23",NaN,NaN,"Piadena, Platina, 40","Capergnanica, XI febbraio, 7"
13,"Trigolo, Roma, 26",NaN,NaN,"Isola Dovarese, Giacomo Matteotti, 1","Ostiano, Mazzini, 1"
14,"Soresina, Giacomo Matteotti, 6",NaN,NaN,"Ostiano, Mazzini, 1",NaN
15,"Ostiano, Mazzini, 1",NaN,NaN,"Ostiano, Mazzini, 1",NaN

In [62]:
#Given a list of cities it return False if "to_insert" is already present
#Return True if "to_insert" isn't present and it will give the index of the best position
def check_insert(schedule_day_list, to_insert, dframe):
    if to_insert in list(schedule_day_list.dropna()):
        return False, -1
    else:
        #schedule_day_list = cities_list(new_route(schedule_day_list, dframe))
        to_return = best_index(schedule_day_list, new_route(schedule_day_list, dframe), to_insert, dframe)
        return True, to_return

#Given: city list wich to_insert come, the city "to_insert" to be moved, 
#the city list where "to_insert" will be insered, the index of the best position and a dataframe
#the function return the improvement
#If negative the exchange mustn't be done, if positive you gain some time
def improvement(f_l, to_insert, t_l, index, dframe):
    from_list = f_l[:]
    from_time = sum(new_route(from_list, dframe).values)
    from_list.remove(to_insert)
    from_time_removed = sum(new_route(from_list, dframe).values)
    
    to_list = t_l[:]
    to_time = sum(new_route(to_list, dframe).values)
    try:
        to_list.insert(index, to_insert)
    except:
        print(to_list)
    to_time_insert = sum(new_route(to_list, dframe).values)
    
    return (from_time-from_time_removed) + (to_time-to_time_insert)

In [63]:
def get_best_improvement(curr_day, from_vehicle, to_vehicle, best_improvement, best_day, best_vehicle, best_idx, to_insert, curr_f_list, fur1_copy, fur2_copy):
    local_improvement = ""
    if(to_vehicle==1):
        days = ["lunedi", "martedi", "mercoledi", "giovedi", "venerdi"]
    else:
        days = ["martedi", "mercoledi", "giovedi"]
        
    for inner_day in days:
        if(to_vehicle==1):
            curr_to_list = list(fur1_copy[inner_day].dropna())
        else:
            curr_to_list = list(fur2_copy[inner_day].dropna())
           
        #print(inner_day)
        if inner_day == curr_day and from_vehicle == to_vehicle:
            #print("continua")
            continue
        else:
            boo, index = check_insert(curr_to_list, to_insert, dft)
        if boo:
            local_improvement = improvement(curr_f_list, to_insert, curr_to_list, index, dft)
        else:
            continue

        #If there's an improvement we update "best" variables, in other case we skip to next day
        #print(local_improvement)
        if local_improvement=="":
            continue
        elif local_improvement>best_improvement:
            best_improvement = local_improvement
            best_day = inner_day
            best_vehicle = to_vehicle
            best_idx = index
        else:
            continue
    return best_improvement, best_day, best_vehicle, best_idx

In [64]:
#For every day of every veichle we get every Location
#We compare the improvement removing this location from the day/veichle routing list and inserting it 
#in the other day/veichle routing lists.
#The location will be moved only if the improvement is positive 
#In case of different positive improvement we move in the higher
pudding = 50
week = ["lunedi", "martedi", "mercoledi", "giovedi", "venerdi"]
short_week = ["martedi", "mercoledi", "giovedi"]
fur1_copy = pd.DataFrame({})
fur1_copy['col'] = pd.Series([0]*pudding)
fur1_copy = fur1_copy.join(fur1)

fur2_copy = pd.DataFrame({})
fur2_copy['col'] = pd.Series([0]*pudding)
fur2_copy = fur2_copy.join(fur2)

for day in week:
    #day="lunedi"
    print(day, end="###\n")
    curr_from_list = list(fur1_copy[day].dropna())
    to_insert_list = list(fur1_copy[day].dropna())
    #print(to_insert_list)
    #to_insert_list.remove("Ostiano, Mazzini, 1")
    #curr_from_list.remove("Ostiano, Mazzini, 1")
    cycles = len(to_insert_list)
    #For every location in this schedule
    for i in range(1, cycles-1):
        #print(to_insert_list)
        to_insert = to_insert_list.pop(0)
        #print(to_insert, end=", ")

        best_improvement = -1000
        best_day = ""
        best_vehicle = ""
        best_idx = ""
        #Here we must compare every possible insert in other days
        #Cycle for first veichle
        best_improvement, best_day, best_vehicle, best_idx = get_best_improvement(day, 1, 1, best_improvement, best_day, best_vehicle, best_idx, to_insert, curr_from_list, fur1_copy, fur2_copy)
        best_improvement, best_day, best_vehicle, best_idx = get_best_improvement(day, 1, 2, best_improvement, best_day, best_vehicle, best_idx, to_insert, curr_from_list, fur1_copy, fur2_copy)

        #If best_day isn't modified where isn't an improvement for every day/veichle
        if(best_improvement==-1000):
            continue
        else:
            #Remove from origin list and insert into target list
            curr_from_list.remove(to_insert)
            
            if(best_vehicle==1):
                #print(f"{to_insert} miglioramento veicolo 1 a {best_day}")
                temp_list = list(fur1_copy[best_day].dropna())
                temp_list.insert(best_idx, to_insert)
                #temp_list.append("Ostiano, Mazzini, 1")
                padding = pd.Series([np.nan]*(pudding-len(temp_list)))
                temp_list = pd.concat([pd.Series(temp_list), padding], ignore_index=True)
                #fur1_copy[best_day] = fur1_copy[best_day].replace(list(fur1_copy[best_day]), temp_list)
                fur1_copy[best_day] = pd.Series(temp_list).values

            elif(best_vehicle==2):
                #print(f"{to_insert} miglioramento veicolo 2 a {best_day}")
                temp_list = list(fur2_copy[best_day].dropna())
                temp_list.insert(best_idx, to_insert)
                #temp_list.append("Ostiano, Mazzini, 1")
                padding = pd.Series([np.nan]*(pudding-len(temp_list)))
                temp_list = pd.concat([pd.Series(temp_list), padding], ignore_index=True)
                #fur2_copy[best_day] =  fur2_copy[best_day].replace(list(fur2_copy[best_day]), temp_list)
                fur2_copy[best_day] = pd.Series(temp_list).values
    padding = pd.Series([np.nan]*(pudding-len(curr_from_list)))
    curr_from_list = pd.concat([pd.Series(curr_from_list), padding], ignore_index=True)
    fur1_copy[day] = pd.Series(curr_from_list).values
fur1_copy

lunedi###

AttributeError: 'list' object has no attribute 'dropna'

In [39]:
#For every day of every veichle we get every Location
#We compare the improvement removing this location from the day/veichle routing list and inserting it 
#in the other day/veichle routing lists.
#The location will be moved only if the improvement is positive 
#In case of different positive improvement we move in the higher
pudding = 50

for day in short_week:
    #day="lunedi"
    print(day, end="###\n")
    curr_from_list = list(fur2_copy[day].dropna())
    to_insert_list = list(fur2_copy[day].dropna())
    #print(to_insert_list)
    #to_insert_list.remove("Ostiano, Mazzini, 1")
    #curr_from_list.remove("Ostiano, Mazzini, 1")
    cycles = len(to_insert_list)
    #For every location in this schedule
    for i in range(1, cycles-1):
        #print(to_insert_list)
        to_insert = to_insert_list.pop(0)
        #print(to_insert, end=", ")
        #to_insert = to_insert_list.pop(0)

        best_improvement = -1000
        best_day = ""
        best_veichle = ""
        best_idx = ""
        #Here we must compare every possible insert in other days
        #Cycle for first veichle
        best_improvement, best_day, best_veichle, best_idx = get_best_improvement(day, 2, 1, best_improvement, best_day, best_veichle, best_idx, to_insert, curr_from_list, fur1_copy, fur2_copy)
        best_improvement, best_day, best_veichle, best_idx = get_best_improvement(day, 2, 2, best_improvement, best_day, best_veichle, best_idx, to_insert, curr_from_list, fur1_copy, fur2_copy)

        #If best_day isn't modified where isn't an improvement for every day/veichle
        if(best_improvement==-1000):
            continue
        else:
            #Remove from origin list and insert into target list
            curr_from_list.remove(to_insert)
            
            if(best_veichle==1):
                #print(f"{to_insert} miglioramento veicolo 1 a {best_day}")
                temp_list = list(fur1_copy[best_day].dropna())
                temp_list.insert(best_idx, to_insert)
                #temp_list.append("Ostiano, Mazzini, 1")
                padding = pd.Series([np.nan]*(pudding-len(temp_list)))
                temp_list = pd.concat([pd.Series(temp_list), padding], ignore_index=True)
                #fur1_copy[best_day] = fur1_copy[best_day].replace(list(fur1_copy[best_day]), temp_list)
                fur1_copy[best_day] = pd.Series(temp_list).values

            elif(best_veichle==2):
                #print(f"{to_insert} miglioramento veicolo 2 a {best_day}")
                temp_list = list(fur2_copy[best_day].dropna())
                temp_list.insert(best_idx, to_insert)
                temp_list.insert(best_idx, to_insert)
                #temp_list.append("Ostiano, Mazzini, 1")
                padding = pd.Series([np.nan]*(pudding-len(temp_list)))
                temp_list = pd.concat([pd.Series(temp_list), padding], ignore_index=True)
                #fur2_copy[best_day] =  fur2_copy[best_day].replace(list(fur2_copy[best_day]), temp_list)
                fur2_copy[best_day] = pd.Series(temp_list).values
    padding = pd.Series([np.nan]*(pudding-len(curr_from_list)))
    curr_from_list = pd.concat([pd.Series(curr_from_list), padding], ignore_index=True)
    fur2_copy[day] = pd.Series(curr_from_list).values
fur2_copy

martedi###
mercoledi###
giovedi###

,col,martedi,mercoledi,giovedi
0,0,"Cremona, Sesto 39","Cremona, Sesto 39","Cremona, Sesto 39"
1,0,"Crema, Civerchi, 9","Crema, Civerchi, 9","Solarolo Rainerio, Giuseppina, 81"
2,0,"Crema, Civerchi, 9","Crema, Civerchi, 9","San Giovanni in Croce, Feudatari, 25 A"
3,0,"Cremona, Ugolani Dati, 4","Cremona, Ugolani Dati, 4",NaN
4,0,"Cremona, Ugolani Dati, 4","Cremona, Ugolani Dati, 4",NaN
5,0,"Solarolo Rainerio, Giuseppina, 81","Casalmaggiore, Guglielmo Marconi, 8",NaN
6,0,"San Giovanni in Croce, Feudatari, 25 A","Viadana, A. Manzoni, 2",NaN
7,0,NaN,"Viadana, A. Manzoni, 2",NaN
8,0,NaN,"Gussola, Comaschi, 1",NaN
9,0,NaN,"Gussola, Comaschi, 1",NaN
10,0,NaN,"San Giovanni in Croce, Feudatari, 25 A",NaN
11,0,NaN,NaN,NaN
12,0,NaN,NaN,NaN
13,0,NaN,NaN,NaN
14,0,NaN,NaN,NaN
15,0,NaN,NaN,NaN
16,0,NaN,NaN,NaN
17,0,NaN,NaN,NaN
18,0,NaN,NaN,NaN
19,0,NaN,NaN,NaN
20,0,NaN,NaN,NaN
21,0,NaN,NaN,NaN
22,0,NaN,NaN,NaN
23,0,NaN,NaN,NaN
24,0,NaN,NaN,NaN
25,0,NaN,NaN,NaN
26,0,NaN,NaN,NaN
27,0,NaN,NaN,NaN
28,0,NaN,NaN,NaN
29,0,NaN,NaN,NaN
30,0,NaN,NaN,NaN
31,0,NaN,NaN,NaN
32,0,NaN,NaN,NaN
33,0,NaN,NaN,NaN
34,0,NaN,NaN,NaN
35,0,NaN,NaN,NaN
36,0,NaN,NaN,NaN
37,0,NaN,NaN,NaN
38,0,NaN,NaN,NaN
39,0,NaN,NaN,NaN
40,0,NaN,NaN,NaN
41,0,NaN,NaN,NaN
42,0,NaN,NaN,NaN
43,0,NaN,NaN,NaN
44,0,NaN,NaN,NaN
45,0,NaN,NaN,NaN
46,0,NaN,NaN,NaN
47,0,NaN,NaN,NaN
48,0,NaN,NaN,NaN
49,0,NaN,NaN,NaN

In [40]:
fur1_copy

,col,lunedi,martedi,mercoledi,giovedi,venerdi
0,0,"Cremona, Sesto 39","Cremona, Sesto 39","Cremona, Sesto 39","Cremona, Sesto 39","Cremona, Sesto 39"
1,0,"Casalpusterlengo, Pusterla 7","Cremona, Felice Cavallotti, 2","Manerbio, INSURREZIONE NAZIONALE","Cremona, Sesto 39","Persico Dosimo, Albert ,7"
2,0,"Pizzighettone, Giuseppe Garibaldi, 18","Bonemerse, Roma, 25","Cremona, Ugolani Dati, 4","Ostiano, Mazzini, 1","Annicco, Giuseppe Garibaldi, 6"
3,0,"Sesto ed Uniti, Roma, 4","Sospiro, Tosi","Casalbuttano ed Uniti, Jacini, 23","Ostiano, Mazzini, 1","Soresina, Giacomo Matteotti, 6"
4,0,"Grumello Cremonese ed Uniti, Roma, 2","Cremona, Palosca n. 2","Castelverde, Ubaldo Ferrari, 15",NaN,"Paderno Ponchielli, Municipio, 3"
5,0,"San Bassano, Mons. Frosi","Gadesco-Pieve Delmona, Giovanni Lonati 9","Crema, Civerchi, 9",NaN,"Pizzighettone, Giuseppe Garibaldi, 18"
6,0,"Castelleone, Roma, 67","Persico Dosimo, Albert ,7","Capralba, Piave, 2",NaN,"Castelleone, Roma, 67"
7,0,"Madignano, Portici, 4","Cremona, Ugolani Dati, 4","Vailate, Dante Alighieri, 7",NaN,"Montodine, XXV Aprile, 10"
8,0,"Izano, Gerardo da Izano, 4/C","Manerbio, INSURREZIONE NAZIONALE","Casaletto Vaprio, Maggiore, 7",NaN,"Ripalta Cremasca, Roma, 5"
9,0,"Trigolo, Roma, 26","Ostiano, Mazzini, 1","Trescore Cremasco, Vittorio Veneto, 1",NaN,"Offanengo, Clavelli Martini, 5"
10,0,"Fiesco, Giuseppe Parini, 10","Ostiano, Mazzini, 1","Spino d'Adda, Circonvallazione, 13",NaN,"Crema, Civerchi, 9"
11,0,"Soncino, Dante Alighieri, 23",NaN,"Rivolta d'Adda, Stefano Renzi, 5",NaN,"Casaletto Vaprio, Maggiore, 7"
12,0,"Offanengo, Clavelli Martini, 5",NaN,"Agnadello, Marconi, 6",NaN,"Palazzo Pignano, Marco Polo, 31"
13,0,"Crema, Civerchi, 9",NaN,"Dovera, Oldrini 2",NaN,"Bagnolo Cremasco, Roma, 3"
14,0,"Soresina, Giacomo Matteotti, 6",NaN,"Pandino, Castello, 15",NaN,"Monte Cremasco, Roma, 12"
15,0,"San Giovanni in Croce, Feudatari, 25 A",NaN,"Pianengo, Nenni",NaN,"Vaiano Cremasco, Gloriosi Caduti, 3"
16,0,"Rivarolo del Re ed Uniti, Giovanni XXIII, 5",NaN,"Camisano, Trieste, 57",NaN,"Pandino, Castello, 15"
17,0,"Martignana di Po, Libertà, 64",NaN,"Casale Cremasco-Vidolasco, Roma, 56",NaN,"Spino d'Adda, Circonvallazione, 13"
18,0,"Gussola, Comaschi, 1",NaN,"Sergnano, IV Novembre, 10",NaN,"Rivolta d'Adda, Stefano Renzi, 5"
19,0,"Viadana, A. Manzoni, 2",NaN,"Ricengo, Guglielmo Marconi",NaN,"Agnadello, Marconi, 6"
20,0,"Casalmaggiore, Guglielmo Marconi, 8",NaN,"Offanengo, Clavelli Martini, 5",NaN,"Capergnanica, XI febbraio, 7"
21,0,"Scandolara Ravara, Italia",NaN,"Soncino, Dante Alighieri, 23",NaN,"Pescarolo ed Uniti, Giuseppe Mazzini, 73"
22,0,"Cingia de' Botti, Giuseppina, 79",NaN,"Romanengo, Guaiarini, 14",NaN,"Vescovato, Roma, 44"
23,0,"Piadena, Platina, 40",NaN,"Grontardo, Roma, 16",NaN,"Ostiano, Mazzini, 1"
24,0,"Isola Dovarese, Giacomo Matteotti, 1",NaN,"Persico Dosimo, Albert ,7",NaN,NaN
25,0,"Sospiro, Tosi",NaN,"Gadesco-Pieve Delmona, Giovanni Lonati 9",NaN,NaN
26,0,"Pescarolo ed Uniti, Giuseppe Mazzini, 73",NaN,"Vescovato, Roma, 44",NaN,NaN
27,0,"Ostiano, Mazzini, 1",NaN,"San Giovanni in Croce, Feudatari, 25 A",NaN,NaN
28,0,NaN,NaN,"Rivarolo del Re ed Uniti, Giovanni XXIII, 5",NaN,NaN
29,0,NaN,NaN,"Casalmaggiore, Guglielmo Marconi, 8",NaN,NaN
30,0,NaN,NaN,"Piadena, Platina, 40",NaN,NaN
31,0,NaN,NaN,"Ostiano, Mazzini, 1",NaN,NaN
32,0,NaN,NaN,NaN,NaN,NaN
33,0,NaN,NaN,NaN,NaN,NaN
34,0,NaN,NaN,NaN,NaN,NaN
35,0,NaN,NaN,NaN,NaN,NaN
36,0,NaN,NaN,NaN,NaN,NaN
37,0,NaN,NaN,NaN,NaN,NaN
38,0,NaN,NaN,NaN,NaN,NaN
39,0,NaN,NaN,NaN,NaN,NaN
40,0,NaN,NaN,NaN,NaN,NaN
41,0,NaN,NaN,NaN,NaN,NaN
42,0,NaN,NaN,NaN,NaN,NaN
43,0,NaN,NaN,NaN,NaN,NaN
44,0,NaN,NaN,NaN,NaN,NaN
45,0,NaN,NaN,NaN,NaN,NaN
46,0,NaN,NaN,NaN,NaN,NaN
47,0,NaN,NaN,NaN,NaN,NaN
48,0,NaN,NaN,NaN,NaN,NaN
49,0,NaN,NaN,NaN,NaN,NaN

In [10]:
fur1_copy.to_csv("../Dati/turni_f/multi_veich_LS1.csv", sep=";", index=False)
fur2_copy.to_csv("../Dati/turni_f/multi_veich_LS2.csv", sep=";", index=False)

In [ ]:
fur2_copy = pd.DataFrame({})
fur2_copy['col'] = pd.Series([np.nan]*50)
fur2_copy = fur2_copy.join(fur2)
fur2_copy[["martedi", "mercoledi", "giovedi"]]

In [ ]:
fur1_copy = pd.DataFrame({})
fur1_copy['col'] = pd.Series([0]*50)
fur1_copy = fur1_copy.join(fur1)
temp_list = pd.Series(["ciao"])
padding=pd.Series([np.nan]*(50-len(temp_list)))
temp_list = pd.concat([temp_list, padding], ignore_index=True)
fur1_copy[best_day] = fur1_copy[best_day].replace(list(fur1_copy[best_day]), temp_list)